package ecs

import (
	"fmt"
	"io/ioutil"
	"net/http"
)

func (c *Client) GetInstanceID() string {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://100.100.100.200/latest/meta-data/instance-id")
	if err != nil {
		fmt.Println("Erro when get instanceID from metadata, ", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		bodyBytes, err2 := ioutil.ReadAll(resp.Body)
		if err2 != nil {
			fmt.Println("Erro when read response body, ", err)
		}
		instanceID := string(bodyBytes)
		fmt.Println("Got Instance ID : ", instanceID)
		return instanceID
	}

	return ""
}
